version: 43
jobs:
- name: Build Docker Image
  steps:
  - type: CheckoutStep
    name: Checkout Code
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: Get Caddy Version
    runInContainer: true
    image: '@server@/itdwgmbh/ci-image:latest'
    interpreter:
      type: DefaultInterpreter
      commands: |
        (curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r '.tag_name') > buildVersion
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: SetBuildVersionStep
    name: Set Build Version
    buildVersion: '@file:buildVersion@'
    condition: SUCCESSFUL
    optional: false
  - type: BuildImageStep
    name: Build Caddy Image
    output:
      type: RegistryOutput
      tags: crvp-nbg1-01.itinfra.cloud/library/caddy:latest crvp-nbg1-01.itinfra.cloud/library/caddy:@build_version@
    registryLogins:
    - registryUrl: '@server@'
      userName: '@job_token@'
      passwordSecret: access-token
    platforms: linux/amd64,linux/arm64
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  - type: ScheduleTrigger
    cronExpression: 0 15 10 ? * 6#3
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
