name: Dependabot auto-merge
on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: itdwgmbh
          repositories: caddy

      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Auto-merge
        run: gh pr merge --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
