name: Build and Upload Caddy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '28 3 1 * *' 
  workflow_dispatch:

env:
  GO_VERSION: 1.22
  XCADDY_SUDO: 0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    outputs:
      caddy_sanitized_version: ${{ steps.sanitize.outputs.caddy_version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest releases
        id: get_releases
        run: |
          caddy_latest_release=$(curl --silent "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)
          echo "caddy_release_tag=$caddy_latest_release" >> $GITHUB_ENV
  
      - name: Sanitize version numbers
        id: sanitize
        run: |
          caddy_sanitized_version=$(echo "${{ env.caddy_release_tag }}" | sed 's/[^0-9.]*//g')
          echo "caddy_version=$caddy_sanitized_version" >> $GITHUB_ENV
          echo "caddy_version=$caddy_sanitized_version" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build Caddy
        run: |
          mkdir -p output
          GOARCH=${{ matrix.arch }} xcaddy build \
            --with github.com/caddy-dns/infomaniak \
            --with github.com/caddy-dns/bunny \
            --with github.com/digilolnet/caddy-bunny-ip \
            --with github.com/caddy-dns/powerdns \
            --output output/caddy-${{ matrix.arch }}

      - name: Create directory structure and control files
        run: |
          # Create directory structures
          mkdir -p caddy_pkg/DEBIAN 
          mkdir -p caddy_pkg/usr/local/bin
          mkdir -p caddy_pkg/etc/caddy
          mkdir -p caddy_pkg/lib/systemd/system

          # Move binary to package directory
          mv output/caddy-${{ matrix.arch }} caddy_pkg/usr/local/bin/caddy

          # Move the Caddyfile to the package directory
          mv Caddyfile caddy_pkg/etc/caddy/Caddyfile

          # Move the systemd service file to the package directory
          mv caddy.service caddy_pkg/lib/systemd/system/caddy.service

          # Move the post-install script to the package directory
          mv postinst caddy_pkg/DEBIAN/postinst

          # Move the post-remove script to the package directory
          mv postrm caddy_pkg/DEBIAN/postrm

          # Set permissions
          chmod +x caddy_pkg/usr/local/bin/caddy
          chmod +x caddy_pkg/DEBIAN/postinst
          chmod +x caddy_pkg/DEBIAN/postrm

          # Create control files
          echo "Package: caddy" > caddy_pkg/DEBIAN/control
          echo "Version: ${{ env.caddy_version }}" >> caddy_pkg/DEBIAN/control
          echo "Section: web" >> caddy_pkg/DEBIAN/control
          echo "Priority: optional" >> caddy_pkg/DEBIAN/control
          echo "Architecture: ${{ matrix.arch }}" >> caddy_pkg/DEBIAN/control
          echo "Maintainer: IT-DW GmbH <support@it-dw.com>" >> caddy_pkg/DEBIAN/control
          echo "Description: Caddy is a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go. This package provides the ${{ matrix.arch }} binary." >> caddy_pkg/DEBIAN/control

      - name: Build DEB package
        run: |
          dpkg-deb --build caddy_pkg
          # Rename the package to include the version number and architecture
          mv caddy_pkg.deb caddy_${{ env.caddy_version }}_${{ matrix.arch }}.deb
    
      - name: Upload DEB packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: caddy-deb-${{ matrix.arch }}
          path: caddy_${{ env.caddy_version }}_${{ matrix.arch }}.deb
    

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: build
    env:
      RCLONE_DIR: /home/runner/.config/rclone
      RCLONE_CONF: /home/runner/.config/rclone/rclone.conf
      caddy_sanitized_version: ${{ needs.build.outputs.caddy_sanitized_version }}
  
    steps:
      - name: Install rclone securely
        run: |
          sudo apt install rclone -y

      - name: Configure rclone
        run: |
            mkdir -p ${{ env.RCLONE_DIR }}
            cat <<EOF > ${{ env.RCLONE_CONF }}
            [gos3]
            type = s3
            provider = Other
            access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            endpoint = https://gos3.io
            EOF
    
      - name: Download existing repository from S3 (if exists)
        run: |
          mkdir -p repo/pool/main/caddy/amd64
          mkdir -p repo/pool/main/caddy/arm64
          rclone copy gos3:itdw-artifacts/caddy/ repo/ --config ${{ env.RCLONE_CONF }} || echo "No existing repository found"
    
      - name: Download DEB AMD64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: caddy-deb-amd64
          path: ./repo/pool/main/caddy/amd64

      - name: Download DEB ARM64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: caddy-deb-arm64
          path: ./repo/pool/main/caddy/arm64
      
      - name: Install required tools
        run: |
          sudo apt-get install -y dpkg-sig gnupg apt-utils
    
      - name: Ensure dists directory structure exists
        run: |
          mkdir -p repo/dists/stable/main/binary-amd64
          mkdir -p repo/dists/stable/main/binary-arm64

      - name: Generate Packages file for amd64
        run: |
          cd repo
          apt-ftparchive packages pool/main/restic/amd64 > dists/stable/main/binary-amd64/Packages
          apt-ftparchive packages pool/main/resticprofile/amd64 >> dists/stable/main/binary-amd64/Packages
          gzip -c dists/stable/main/binary-amd64/Packages > dists/stable/main/binary-amd64/Packages.gz
    
      - name: Generate Packages file for arm64
        run: |
          cd repo
          apt-ftparchive packages pool/main/restic/arm64 > dists/stable/main/binary-arm64/Packages
          apt-ftparchive packages pool/main/resticprofile/arm64 >> dists/stable/main/binary-arm64/Packages
          gzip -c dists/stable/main/binary-arm64/Packages > dists/stable/main/binary-arm64/Packages.gz
          
      - name: Generate new Release file
        run: |
            (cd repo && apt-ftparchive release \
              -o APT::FTPArchive::Release::Origin="IT-DW GmbH" \
              -o APT::FTPArchive::Release::Label="IT-DW Repository" \
              -o APT::FTPArchive::Release::Suite="stable" \
              -o APT::FTPArchive::Release::Codename="stable" \
              -o APT::FTPArchive::Release::Architectures="amd64 arm64" \
              -o APT::FTPArchive::Release::Components="main" \
              -o APT::FTPArchive::Release::Description="Caddy Web-Server Packages" \
              dists/stable > dists/stable/Release)

      - name: Sign the Release file
        env:
          GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # Import the GPG key
          echo "$GPG_KEY" | gpg --batch --import
          
          # Sign the Release file to create a detached signature (Release.gpg)
          gpg --batch --yes --pinentry-mode loopback --passphrase "$PASSPHRASE" -abs -o repo/dists/stable/Release.gpg repo/dists/stable/Release
          
          # Create the InRelease file by signing the Release file with a clearsign method
          gpg --batch --yes --pinentry-mode loopback --passphrase "$PASSPHRASE" --clearsign -o repo/dists/stable/InRelease repo/dists/stable/Release
          
          # Clear the GPG key from the environment
          gpg --batch --delete-secret-keys
          gpg --batch --delete-keys

      - name: Sync repository to S3
        run: |
            rclone sync repo/ gos3:itdw-artifacts/caddy -v --config ${{ env.RCLONE_CONF }} --checksum
          
      - name: Send POST request with release.txt content
        run: |
          curl -X POST https://hc.itdw.io/ping/bf3e2777-2707-4bf0-b22f-d13af430e8c3 \
            -H "Content-Type: text/plain" \
            --data-binary @$${{ env.TEMP_DIR }}/release.txt
